### ISSUE TITLE
BATCH_FINALIZE and BATCH_FINISH listeners not calling

### ISSUE THREAD

**Issue by csexplorer** [rpldy/react-uploady#533]
After uploading successfully saved to server, not calling finish or finalize listeners. In the code below works only BATCH_START and BATCH_PROGRESS. In BATCH_START listener I set status to 'uploading' and in BATCH_FINISH set to 'uploaded',  but in BATCH_FINISH listener not calling

**Expected behavior**
After finishing upload must be called finalize and finish listeners. I want to disable some ui elements according to **uploading state**

**Versions**
@rpldy/uploady => V1.3.1

**Code**
```
const Uploader: React.FC<IProps> = ({ activeIndex }) => {

  const accessToken = storage.local.get(config.api.access_token_key);

  return (
    <Uploady
      key={accessToken}
      destination={{
        method: 'POST',
        url: `${config.api.base_url}${config.services.file}/v1/seller/product/image`,
        headers: {
          Authorization: `Bearer ${accessToken}`
        }
      }}
      concurrent
      maxConcurrent={5}
      grouped={false}
      listeners={{
        [UPLOADER_EVENTS.BATCH_FINALIZE]: data => {
          console.log('BATCH_FINALIZE', data);
        },
        [UPLOADER_EVENTS.BATCH_START]: data => {
          console.log('BATCH_START', data);
        },
        [UPLOADER_EVENTS.BATCH_PROGRESS]: data => {
          console.log('BATCH_PROGRESS', data);
        },
        [UPLOADER_EVENTS.BATCH_ABORT]: data => {
          console.log('BATCH_ABORT', data);
        },
        [UPLOADER_EVENTS.BATCH_ERROR]: data => {
          console.log('BATCH_ERROR', data);
        },
        [UPLOADER_EVENTS.BATCH_FINISH]: data => {
          console.log('BATCH_FINISH', data);
        }
      }}
    >
      <Dropzone {...{ activeIndex }} />
    </Uploady>
  );
};
```
Dropzone component content:
```
const Dropzone: React.FC<IProps> = ({ activeIndex }) => {
  const { values, errors } = useFormikContext<IForm.Create | IForm.Update>();
  const { showFileUpload } = useUploadyContext();

  const imagesLength = (get(values.groups[activeIndex], 'imageIds') || []).length;

  return (
    <>
      <div className={cx(classes.wrapper, !!get(errors.groups, `[${activeIndex}][imageIds]`) && classes.wrapperError)}>
        <div className={classes.content}>
          <Grid.Row gutter={[12, 12]} justify={!imagesLength ? 'center' : undefined}>
            <FileList {...{ activeIndex }} />

            {!!imagesLength && !(imagesLength >= 15) && (
              <Grid.Col
                onClick={e => {
                  showFileUpload();
                }}
              >
                <SimpleUploader onSelect={() => {}} type="image" />
              </Grid.Col>
            )}

            {!imagesLength && (
              <Grid.Col onClick={e => {
                  showFileUpload();
                }}>
                <StateIcon variant="info" icon={<Icon name="CameraAdd" />} />
              </Grid.Col>
            )}
          </Grid.Row>
        </div>
      </div>
    </>
  );
};
```

**Comment by yoavniran** [comment]
hi @csexplorer please upgrade to the latest version: [1.4.1](https://github.com/rpldy/react-uploady/releases/tag/v1.4.1) and let me know if the issue still persists.

I've made some fixes in this area not long ago.

If you still see the problem, please create a simple reproducing sandbox that I'll be able to test

**Comment by csexplorer** [comment]
hi @yoavniran, thank you for suggestion, but if i upgrade my version to 1.4.1, I am receiving error in console like this
```
uploader.queue: sender failed with unexpected error TypeError: Object(...) is not a function
    at Object.send (batchItemsSender.js:31:1)
    at sendAllowedItems (processBatchItems.js:35:1)
    at processBatchItems.js:132:1
```

**Comment by csexplorer** [comment]
I enabled debug model in **Uploady** component

**Comment by yoavniran** [comment]
make sure you upgrade all Uploady dependencies 
If its still failing, I'll need a reproducing sandbox/repository to check

**Comment by csexplorer** [comment]
okay, I'll try
