### ISSUE TITLE
Nextjs: ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by anonymous-coder** [rpldy/react-uploady#68]
Keep getting this error, i have 'babel/next' in my babelrc file. 

`ReferenceError: regeneratorRuntime is not defined
    at /Users/m5/projects/meet_apps/pwa/node_modules/@rpldy/uploader/lib/queue/batchHelpers.js:104:46
    at Object.<anonymous> (/Users/m5/projects/meet_apps/pwa/node_modules/@rpldy/uploader/lib/queue/batchHelpers.js:136:2)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/m5/projects/meet_apps/pwa/node_modules/@rpldy/uploader/lib/queue/processFinishedRequest.js:12:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/m5/projects/meet_apps/pwa/node_modules/@rpldy/uploader/lib/queue/processBatchItems.js:12:54)`

not sure what other information to provide as i can't get past the example with custom button  in my Nextjs app

**Comment by yoavniran** [comment]
Hey @anonymous-coder can you share a reproducing repo or sandbox?

**Comment by yoavniran** [comment]
In any case. this should be helpful: https://github.com/babel/babel/issues/9849#issuecomment-487040428

**Comment by anonymous-coder** [comment]
Ty, you can close this, i really shouldn't have bothered you with this. Excited to put your package in my project for production btw

**Comment by yoavniran** [comment]
no problem. Really happy to hear it! 
Would love to hear about your use-case for Uploady

**Comment by efriandika** [comment]
Hi.. Is id possible to avoid `regenerator-runtime` use in this library?
